# Generated by Django 5.0.6 on 2024-06-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizName', models.CharField(default='Unnamed Quiz', max_length=128, unique=True)),
                ('passage', models.CharField(max_length=512)),
                ('questions', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
