# Generated by Django 5.0.6 on 2024-06-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passage',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quizName',
            field=models.CharField(default='Unnamed Quiz', max_length=128),
        ),
    ]
