# Generated by Django 5.0.6 on 2024-06-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='questionoptions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'managed': True},
        ),
    ]
