# Generated by Django 5.0.6 on 2024-06-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_file_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='questionoptions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'managed': False},
        ),
    ]
