# Generated by Django 5.0.6 on 2024-06-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_file_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiQuiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quizname', models.CharField(db_column='quizName', max_length=128)),
                ('passage', models.CharField(max_length=4096)),
                ('questions', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'api_quiz',
                'managed': False,
            },
        ),
    ]
