# Generated by Django 5.0.6 on 2024-06-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apiquiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiQuiz',
        ),
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionoptions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
