# Generated by Django 5.0.6 on 2024-06-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_apiquiz_alter_file_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='id',
            new_name='fileid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='questionid',
        ),
        migrations.RenameField(
            model_name='questionoptions',
            old_name='id',
            new_name='questionoptionid',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='id',
            new_name='topicid',
        ),
    ]
