# Generated by Django 5.0.6 on 2024-07-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_topic_isgenerating_alter_topic_lastmodified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='questionoptions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'managed': False},
        ),
    ]
