# Generated by Django 5.0.6 on 2024-07-24 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_file_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionoptions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
