# Generated by Django 5.0.6 on 2024-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_question_options_alter_questionoptions_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='question',
            name='refdata',
            field=models.TextField(db_column='refData', default=''),
        ),
    ]
