# Generated by Django 5.0.6 on 2024-07-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_topic_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='maxquestions',
            field=models.IntegerField(db_column='maxQuestions', default=0),
        ),
    ]
